name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.17'
          check-latest: true
          cache-dependency-path: subdir/go.sum
      - run: go run hello.go
